language: python
env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON_VERSION
    - source activate testenv
    - conda install --yes --quiet numpy scipy matplotlib scikit-learn pandas jupyter seaborn
    - python -m ipykernel install --user
    - pip install codecov
    - pip install -q flake8
    - git clone https://github.com/paris-saclay-cds/ramp-workflow.git
    - cd ramp-workflow
    - python setup.py install
    - cd ..
script:
    - flake8 *.py submissions/*/*.py
    - jupyter nbconvert --execute iris_test_starting_kit.ipynb
    - coverage run ramp-workflow/rampwf/test_submission.py .
after_success:
    - codecov
notifications:
  email: true
